package in.dbit.byb.PersonalityProfiling;

public class HollandQuest {
    String[] hollandQuest = new String[]{
        "1. Test the quality of parts before shipment ",
        "2. Study the structure of the human body ",
        "3. Conduct a musical choir ",
        "4. Give career guidance to people ",
        "5. Sell restaurant franchises to individuals ",
        "6. Generate the monthly payroll checks for an office ",
        "7. Lay brick or tile ",
        "8. Study animal behavior ",
        "9. Direct a play ",
        "10. Do volunteer work at a non-profit organization ",
        "11. Sell merchandise at a department store ",
        "12. Inventory supplies using a hand-held computer ",
        "13. Work on an offshore oil-drilling rig ",
        "14. Do research on plants or animals ",
        "15. Design artwork for magazines ",
        "16. Help people who have problems with drugs or alcohol ",
        "17. Manage the operations of a hotel ",
        "18. Use a computer program to generate customer bills ",
        "19. Assemble electronic parts ",
        "20. Develop a new medical treatment or procedure ",
        "21. Write a song ",
        "22. Teach an individual an exercise routine ",
        "23. Operate a beauty salon or barber shop ",
        "24. Maintain employee records ",
        "25. Operate a grinding machine in a factory ",
        "26. Conduct biological research ",
        "27. Write books or plays ",
        "28. Help people with family-related problems ",
        "29. Manage a department within a large company ",
        "30. Compute and record statistical and other numerical data ",
        "31. Fix a broken faucet ",
        "32. Study whales and other types of marine life ",
        "33. Play a musical instrument ",
        "34. Supervise the activities of children at a camp ",
        "35. Manage a clothing store ",
        "36. Operate a calculator ",
        "37. Assemble products in a factory ",
        "38. Work in a biology lab ",
        "39. Perform stunts for a movie or television show ",
        "40. Teach children how to read ",
        "41. Sell houses ",
        "42. Handle customers bank transactions ",
        "43. Install flooring in houses ",
        "44. Make a map of the bottom of an ocean ",
        "45. Design sets for plays ",
        "46. Help elderly people with their daily activities ",
        "47. Run a toy store ",
        "48. Keep shipping and receiving records "
    };
}
